# Generated by Django 3.2.5 on 2021-07-11 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import ticket.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('priority', models.CharField(choices=[('h', 'زیاد'), ('m', 'متوسط'), ('l', 'کم')], default='m', max_length=1, verbose_name='اولویت')),
                ('department', models.CharField(choices=[('t', 'فنی'), ('f', 'مالی'), ('o', 'نظر و پیشنهادات')], default='t', max_length=1, verbose_name='بخش')),
                ('status', models.CharField(choices=[('o', 'باز'), ('p', 'در حال بررسی'), ('c', 'بسته شده')], default='o', max_length=1, verbose_name='وضعیت')),
                ('date_created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': '  تیکت\u200cها',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_reply', models.BooleanField(default=False, verbose_name='پاسخ ادمین')),
                ('is_seen', models.BooleanField(default=False, verbose_name='خوانده\u200cشده')),
                ('date_sent', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('body', models.TextField(verbose_name='متن پیام')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': ' پیام\u200cها',
                'ordering': ['-date_sent'],
            },
        ),
        migrations.CreateModel(
            name='AttachmentFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ticket-files/images/', validators=[ticket.utils.size_limit], verbose_name='تصویر')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.message', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'فایل ضمیمه\u200cشده',
                'verbose_name_plural': 'فایل\u200cهای ضمیمه\u200cشده',
            },
        ),
    ]
